### ISSUE TITLE
MKD, ps2, weights don't work

### ISSUE THREAD

**Issue by Tosyk** [leeao/Noesis-Plugins#1]
great code work! :)
not sure if it meant to work that way but it seems I can't get weights to work:
![image](https://user-images.githubusercontent.com/24209966/104531015-4c0f2280-561e-11eb-85a5-f9d15baaf366.png)
could you look at this?
[mkd_ps2_liukang.zip](https://github.com/leeao/Noesis-Plugins/files/5811804/mkd_ps2_liukang.zip)

**Comment by leeao** [comment]
Yes, I didn't add support for skin, because some indexes in the bone ID buffer exceed the number of bones, and the actual number of bones is not so many, which does not match. I think the part about bones still needs to be decrypted. I have no plan for the moment. I will take a look at this part again when I have time.


发件人: Tosyk<mailto:notifications@github.com>
发送时间: 2021年1月14日 9:10
收件人: leeao/Noesis-Plugins<mailto:Noesis-Plugins@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [leeao/Noesis-Plugins] MKD, ps2, weights don't work (#1)


great code work! :)
not sure if it meant to work that way but it seems I can't get weights to work:
[image]<https://user-images.githubusercontent.com/24209966/104531015-4c0f2280-561e-11eb-85a5-f9d15baaf366.png>
could you look at this?
mkd_ps2_liukang.zip<https://github.com/leeao/Noesis-Plugins/files/5811804/mkd_ps2_liukang.zip>

―

**Comment by Tosyk** [comment]
oh, thanks for the reply. it's great that you decided to work on these cool old MK games! :)

**Comment by Tosyk** [comment]
Leeao, haven't you found the solution to the weights?

**Comment by leeao** [comment]
Unfortunately, no. In fact, I re-checked it a few days ago, mainly because I couldn't find the correct way to decode the bone index and weights. I think it can be found only by dynamic reverse engineering of the main program.

**Comment by Tosyk** [comment]
okay, I understand. thanks for checking man.
btw, don't you think it could be similar to standard renderware bone structure?
I found renderware SDK here: https://archive.org/details/RenderwareStudio3.7SDKForWindows
Ii will be awesome if you could find time to check it out.
